UPDATE MINGO.interest SET name = 'Major League Baseball (in general)' WHERE id = 1;
UPDATE MINGO.interest SET name = 'Major League Baseball (National League)' WHERE id = 2;
UPDATE MINGO.interest SET name = 'Major League Baseball (American League)' WHERE id = 3;
UPDATE MINGO.interest SET name = 'Arizona Diamondbacks' WHERE id = 4;
UPDATE MINGO.interest SET name = 'Atlanta Braves' WHERE id = 5;
UPDATE MINGO.interest SET name = 'Baltimore Orioles' WHERE id = 6;
UPDATE MINGO.interest SET name = 'Boston Red Sox' WHERE id = 7;
UPDATE MINGO.interest SET name = 'Chicago Cubs' WHERE id = 8;
UPDATE MINGO.interest SET name = 'Chicago White Sox' WHERE id = 9;
UPDATE MINGO.interest SET name = 'Cincinnati Reds' WHERE id = 10;
UPDATE MINGO.interest SET name = 'Cleveland Indians' WHERE id = 11;
UPDATE MINGO.interest SET name = 'Colorado Rockies' WHERE id = 12;
UPDATE MINGO.interest SET name = 'Detroit Tigers' WHERE id = 13;
UPDATE MINGO.interest SET name = 'Houston Astros' WHERE id = 14;
UPDATE MINGO.interest SET name = 'Kansas City Royals' WHERE id = 15;
UPDATE MINGO.interest SET name = 'Los Angeles Angels' WHERE id = 16;
UPDATE MINGO.interest SET name = 'Los Angeles Dodgers' WHERE id = 17;
UPDATE MINGO.interest SET name = 'Miami Marlins' WHERE id = 18;
UPDATE MINGO.interest SET name = 'Milwaukee Brewers' WHERE id = 19;
UPDATE MINGO.interest SET name = 'Minnesota Twins' WHERE id = 20;
UPDATE MINGO.interest SET name = 'New York Mets' WHERE id = 21;
UPDATE MINGO.interest SET name = 'New York Yankees' WHERE id = 22;
UPDATE MINGO.interest SET name = 'Oakland Athletics' WHERE id = 23;
UPDATE MINGO.interest SET name = 'Philadelphia Phillies' WHERE id = 24;
UPDATE MINGO.interest SET name = 'Pittsburgh Pirates' WHERE id = 25;
UPDATE MINGO.interest SET name = 'San Diego Padres' WHERE id = 26;
UPDATE MINGO.interest SET name = 'San Francisco Giants' WHERE id = 27;
UPDATE MINGO.interest SET name = 'St. Louis Cardinals' WHERE id = 28;
UPDATE MINGO.interest SET name = 'Seattle Mariners' WHERE id = 29;
UPDATE MINGO.interest SET name = 'Tampa Bay Rays' WHERE id = 30;
UPDATE MINGO.interest SET name = 'Texas Rangers' WHERE id = 31;
UPDATE MINGO.interest SET name = 'Toronto Blue Jays' WHERE id = 32;
UPDATE MINGO.interest SET name = 'Washington Nationals' WHERE id = 33;